include:
  - ".cicd/test.yaml"
  - ".cicd/report.yaml"
  # - ".cicd/notification.yaml"
  - ".cicd/collect.yaml"

cache:
  paths:
    - venv

stages:
  - test
  - report
  # - notify
  - collect

variables:
  TG_CHAT_THREAD_ID: "2"
