[project]
name = "petstore"
version = "1.0.0"

[tool.ruff]
line-length = 100
lint.select = [
    "E", # Pycodestyle (PEP 8)
    "F", # Pyflakes (ошибки)
    "B", # flake8-bugbear (потенциальные баги)
    "I", # isort (сортировка импортов)
    "UP", # pyupgrade (современный Python)
    "PL", # Pylint-совместимые правила
    "SIM", # Simpler (упрощение кода)
    "C4", # Complexity (сложность)
    "Q", # Quality (качество кода)
    "UP", # pyupgrade (обновление синтаксиса)
    "W", # Warnings (предупреждения)
    "Q", # Quality (качество кода)
    "PT", # Pytest (тесты)
    "EM", # Плохие сообщения об ошибках
    "G", # Ошибки в логах
    "N", # Неправильные имена
    "RET", # Возврат значений
    "S", # Сложные конструкции
    "RUF", # Ruff-специфичные правила
    "A", # Builtins
    "COM", # commas
    "DTZ", # datetime
    "LOG", # logging
    "G", # logging format
    "RET", # return statements
    "SLF", # self
    "TC", # type checking
    "ARG", # unused arguments
    "PTH", # pathlib
    "PERF", # perflint
#    "D", # Docstrings
]
lint.ignore = [
    "E203", # Пробел перед ':' (конфликт с Black)
    "E501", # Длина строки (уже контролируется Black)
    "S101", # Использование assert (в тестах)
    "PLR0913", # Слишком много аргументов
    "D401", # Повелительное наклонение в docstring
    "D205", # Пробел между строками в docstring
    "D415", # Точка в конце docstring
    "D400",
    "D107", # __init__
    "PLR2004",
    "EM101",
    "EM102",
    "G004",
    "RUF001",
    "RUF002",
    "RUF003",
    "COM812",

]
exclude = [
    ".git",
    "__pycache__",
    "venv",
    "migrations",
    "*.sqlite3",
    "allure-results",
    "allure-report",
    "venv",
]

[tool.black]
line-length = 100
target-version = ["py312"]
#skip-string-normalization = false
exclude = '''
/(
  \.git
  | \.venv
  | migrations
  | __pycache__
  | allure-results
  | allure-report
  | venv
)/
'''

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["petstore"]  # Замените на имя вашего пакета
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"
