POST_PET = "/pet"
POST_UPLOAD_IMAGE = "/pet/{pet_id}/uploadImage"
POST_UPDATE_STATUS_AND_NAME = "/pet/{pet_id}"
GET_FIND_BY_STATUS = "/pet/findByStatus"
GET_FIND_BY_ID = "/pet/{pet_id}"
PUT_PET = "/pet"
DELETE_PET = "/pet/{pet_id}"
