GET_USER_BY_USERNAME = "/user/{username}"
POST_CREATE_USER = "/user"
POST_CREATE_USER_LIST = "/user/createWithList"
POST_CREATE_USER_WITH_ARRAY = "/user/createWithArray"
GET_LOGIN_USER = "/user/login"
GET_LOGOUT_USER = "/user/logout"
PUT_UPDATE_USER = "/user/{username}"
DELETE_USER = "/user/{username}"
